version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:0.4.17
    container_name: sample_chromadb
    ports:
      - 8000:8000
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
